Mach30/kasm-dof-workspace

- README.md
- install_files/pycharm-community-2022.2.2.tar.gz
- playbook.yaml
closes #11 
built & tested locally
> Install pycharm

- .github/workflows/main.yml
- README.md
- playbook.yaml
- reset_kasm_user.sh
closes #3 
resolves #22 as per https://github.com/Mach30/kasm-dof-workspace/pull/18/commits/89b2af961d1049a96017425d63292c2a8baa620d
closes #24 as per https://github.com/Mach30/kasm-dof-workspace/pull/18/commits/733eac72dc1e785699a4e3b072a1902c885ffddc
closes #26 as per https://github.com/Mach30/kasm-dof-workspace/pull/18/commits/bdcf234b73aefe8dd340279655db4e9c3d39cb59
> Install dendron

- playbook.yaml
> Install gradle

- README.md
- playbook.yaml
closes #19
closes #20
closes #21 
closes #7
> update nodejs tools to v18.5.0 and related

- .github/workflows/main.yml
- README.md
- playbook.yaml
> install gradle for java (vs code extension)

- .github/workflows/main.yml
> update CI to resolve deprecated `save-state` command

- .github/workflows/main.yml
- MAINTAINERS.md
> Tag docker images with git tags

- playbook.yaml
> npm install oclif and check version

- README.md
- playbook.yaml
> Fix oclif version & update linkml

- README.md
- playbook.yaml
> Install cli-njk

- README.md
- playbook.yaml
> Update linkml to support polymorphism

- .github/workflows/main.yml
- README.md
- playbook.yaml
> Update gradle version to 8.7

- README.md
- playbook.yaml
closes #65 
closes #51 
closes #59
> Fix yarn version and update node tools

- README.md
- playbook.yaml
> Update oclif version to 4.17.32

- README.md
- playbook.yaml
> Install m30pm version v0.1.0-alpha.4

- .github/workflows/main.yml
- README.md
- playbook.yaml
closes #78 
closes #68 
closes #81 
closes #69 
closes #83 
closes #82
> Install vs code extentions for v3.0.0 release

- playbook.yaml
> Install tree

- Dockerfile
- playbook.yaml
> Fix background wallpaper

- README.md
- playbook.yaml
> Install markedpp

- playbook.yaml
> configure JSON tab size to 2 in vs code settings
